name: Push Docker images
on:
  #schedule:
  #  - cron:  '30 5,17 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'hub/*'
  
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: pull and push images
        shell: bash
        run: |
          dirs="hub"
          pushed_dir="pushed"
          
          for dir in $dirs; do
              for _file in $(ls $dir); do
                  image_file="$dir/$_file"
                  pushed_file="$pushed_dir/$_file"
                  image_tag=$(head -n 1 $image_file | tr -d '[:space:]')
                  pushed_tag=""

                  if [[ -f "$pushed_file" ]]; then
                      pushed_tag=$(head -n 1 $pushed_file | tr -d '[:space:]')
                  fi
                  if [[ "$image_tag" != "$pushed_tag" ]]; then
                      echo 'not pushed yet, now pushing.'
                      docker pull $image_tag
                      docker tag $image_tag ghcr.io/${GITHUB_REPOSITORY_OWNER}/$image_tag
                      docker push ghcr.io/${GITHUB_REPOSITORY_OWNER}/$image_tag
                      echo "$image_tag" > $pushed_file
                  else
                      echo "$image_tag pushed."
                  fi
              done
          done

      - name: apply changes to repo
        uses: stefanzweifel/git-auto-commit-action@v5

    
