name: Push Docker images
on:
  #schedule:
  #  - cron:  '30 5,17 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docker-images/*'
  
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: pull and push images
        shell: bash
        run: |
          docker pull nginx:1.26
          docker tag nginx:1.26 ghcr.io/${GITHUB_REPOSITORY_OWNER}/nginx:1.26
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER}/nginx:1.26



      
